### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by npoulin2378** [mooreatv/AHDBapp#2]
I followed the README and end up with this error at the end. 

~/go/src/github.com/mooreatv/AHDBapp (master)
$ go run ahdb.go < auctiondb.json > auctiondb.csv
12:59:02 I ahdb.go:135> AHDB parser started...
12:59:02 I lua2json.go:85> Using buffer size 16777216
12:59:02 F ahdb.go:150> Unable to unmarshal json result: invalid character '\n' in literal true (expecting 'e')
panic: aborting...

NOTE: I am also using the Classic version. I am not sure if that is compatible or not?

**Comment by mooreatv** [comment]
you don’t need 2 steps anymore, see the end of the readme, ahdb can read the lua directly

**Comment by npoulin2378** [comment]
I apologize for not reading thoroughly enough. 

I am also ignorant to what I am supposed to do after this point: 

17:08:18 I ahdb.go:135> AHDB parser started...
17:08:18 I lua2json.go:85> Using buffer size 16777216

Is there commands that I am supposed to use to filter the items or will it push out a .csv like before?

**Comment by mooreatv** [comment]
I updated https://github.com/mooreatv/AHDBapp#getting-started

- On windows `go\bin\AHDBapp.exe < "c:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\YOURACCOUNT\SavedVariables\AuctionDB.lua" > data.csv`
- On unix/mac `~/go/bin/AHDBapp < ...path_to_.../SavedVariables/AuctionDB.lua > data.csv`

**Comment by npoulin2378** [comment]
I really appreciate your patience. That did work but the only output I got into the .csv was "Linen". Is there a way to specify the item I am looking for?

**Comment by mooreatv** [comment]
not yet without modifying the code, it's work in progress

**Comment by npoulin2378** [comment]
Is it possible to have the code just out push everything? The most important attributes being cost, item number, date when scanned, and just for convenience the name of the item? 

Also I am sorry for throwing all these nagging questions at you.
