### ISSUE TITLE
Error: Unable to unmarshal json result: invalid character '}' looking for beginning of value

### ISSUE THREAD

**Issue by TinyBabyOwl** [mooreatv/AHDBapp#5]
I am running `AHDBapp.exe < "MyPathTo\AuctionDB.lua" > data.csv` and I am getting the following error:

```
13:14:38 I ahdb.go:244> AHDB parser started...
13:14:38 I lua2json.go:85> Using buffer size 16777216
13:14:38 F ahdb.go:259> Unable to unmarshal json result: invalid character '}' looking for beginning of value
panic: aborting...

goroutine 1 [running]:
fortio.org/fortio/log.logPrintf(0x6, 0x6c3d3f, 0x23, 0xc001111f00, 0x1, 0x1)
        C:/Users/newbt/go/src/fortio.org/fortio/log/logger.go:160 +0x4f4
fortio.org/fortio/log.Fatalf(...)
        C:/Users/newbt/go/src/fortio.org/fortio/log/logger.go:208
main.main()
        C:/Users/newbt/go/src/github.com/mooreatv/AHDBapp/ahdb.go:259 +0x1e4
```

**Comment by TinyBabyOwl** [comment]
Same error if I do `go run ahdb.go < "MyPathTo\AuctionDB.lua" > data.csv`

**Comment by mooreatv** [comment]
can you attach your file so I can reproduce the problem?

ps: the current version doesn't produce a csv but imports to mysql btw but still the error shouldn't happen

**Comment by TinyBabyOwl** [comment]
Assuming you want my AuctionDB file. Here you go:
[AuctionDB.zip](https://github.com/mooreatv/AHDBapp/files/3672809/AuctionDB.zip)

**Comment by mooreatv** [comment]
yes, thanks! but it works for me with your file:
```shell
$ time go run ahdb.go < bench/AuctionDB.lua
13:49:31 I ahdb.go:248> AHDB parser started (reading from stdin)...
13:49:31 I lua2json.go:85> Using buffer size 16777216
13:49:31 I lua2json.go:148> Done, 4653 lines converted
13:49:31 I ahdb.go:272> Deserialization done, found 4 scans. ItemDB has 4553 items.
13:49:31 I ahdb.go:220> Starting DB save...
13:49:31 I ahdb.go:158> ItemDB at start has 19122 items
13:49:31 I ahdb.go:202> Inserted/updated 4554 items, 0.37 Mbytes in MySQL DB in 392.9488ms
13:49:31 I ahdb.go:206> ItemDB now has 19790 items
13:49:32 I ahdb.go:106> Inserted 13414 auctions for 3222 items for scanId 6547
13:49:33 I ahdb.go:106> Inserted 13462 auctions for 3238 items for scanId 6548
13:49:34 I ahdb.go:106> Inserted 15175 auctions for 3546 items for scanId 6549
13:49:35 I ahdb.go:106> Inserted 15114 auctions for 3494 items for scanId 6550
13:49:35 I ahdb.go:148> After big commit of all the scans...

real    0m5.545s
user    0m0.000s
sys     0m0.015s
```
I think i've seen it though on an empty ldbi save, let me try to repro that

**Comment by mooreatv** [comment]
if you update you can try
```
$ time go run ahdb.go -nodb < AuctionDB.lua
```

**Comment by TinyBabyOwl** [comment]
Updated and have made some progress. Looks like the parser is working, but it's giving me an empty CSV. 

```
12:53:37 I ahdb.go:274> AHDB parser started (reading from stdin)...
12:53:37 I lua2json.go:85> Using buffer size 16777216
12:53:37 I lua2json.go:148> Done, 5261 lines converted
12:53:37 I ahdb.go:298> Deserialization done, found 5 scans. ItemDB has 5131 items.
12:53:37 I ahdb.go:241> Starting DB save with noDB=true ...
12:53:37 I ahdb.go:226> Parsed 5132 items, 0.42 Mbytes in 0s
12:53:37 I ahdb.go:108> Inserted 13414 auctions for 3222 items for scanId -1
12:53:37 I ahdb.go:108> Inserted 13462 auctions for 3238 items for scanId -1
12:53:37 I ahdb.go:108> Inserted 15175 auctions for 3546 items for scanId -1
12:53:37 I ahdb.go:108> Inserted 15114 auctions for 3494 items for scanId -1
12:53:37 I ahdb.go:108> Inserted 11185 auctions for 2809 items for scanId -1
```

**Comment by mooreatv** [comment]
I fixed the original (json) error now; it should work even if you don't move the AHDB button and thus the ldbi var/array is empty

About CSV, the csv for linen was just a demo; the code now does proper database inserts

I could maybe make it also optionally create CSV but... what is it for? (or you can check the previous code)

**Comment by TinyBabyOwl** [comment]
> About CSV, the csv for linen was just a demo; the code now does proper database inserts

Ah, ok.

> I could maybe make it also optionally create CSV but... what is it for?

I was hoping to use a CSV to use the data in a spreadsheet. But it's no problem. I'll set up a DB and just pull the data in to my spreadsheet.

**Comment by mooreatv** [comment]
cool, I use mysql for windows and it works well, just create the db, set MYSQL_PASSWORD to the password you set during creation, execute schema.sql and then you can import your data

**Comment by TinyBabyOwl** [comment]
What are the commands I need to give AHDB to pass it my DB info? I'm hosting my DB off an external server.

Edit: Never mind, I figured out :)

**Comment by TinyBabyOwl** [comment]
Any idea why I get `Can't count items: Error 1045: Access denied for user 'root'@'localhost' (using password: NO)` when I run ahdb? I've set my password, my DB is running and using the schema you provided. I can connect to my DB with workbench using the same info that ahdb has. I've been banging my head over this.
