### ISSUE TITLE
Error when selecting recipe in Skillet Enchanting

### ISSUE THREAD

**Issue by Malevola** [mooreatv/AHDBapp#6]
Get the following error when I select any recipe from the Skillet Enchanting window. Discord invite has expired, so submitting here.

Bug Report for AuctionDB v1.02.00
2019/12/28 06:46:30 -0800 81f8ddc

Bug report from slash command
Session messages log:
AHDB bug report open: Please submit on discord or https://bit.ly/ahbug or email
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1797: in function `UpdateDetailsWindow'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1209: in function `UpdateTradeSkillWindow'
Interface\AddOns\Skillet-Classic\UI\M...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1797: in function `UpdateDetailsWindow'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:868: in function `UpdateTradeSkillWindow'
Interface\AddOns\Skillet-Classic\UI\Ma...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1797: in function `UpdateDetailsWindow'
Interface\AddOns\Skillet-Classic\Skillet.lua:1267: in function `SetSelectedSkill'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lu...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
Interface\AddOns\Skillet-Classic\Skillet.lua:1266: in function `SetSelectedSkill'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:2227: in function `SkillButton_OnClick'
[string "*:OnClick"]:2: in function <[string...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
Interface\AddOns\Skillet-Classic\Skillet.lua:1266: in function `SetSelectedSkill'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:2227: in function `SkillButton_OnClick'
[string "*:OnClick"]:2: in function <[string...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ce\Add...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1797: in function `UpdateDetailsWindow'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1209: in function `UpdateTradeSkillWindow'
Interface\AddOns\Skillet-Classic\UI\M...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1797: in function `UpdateDetailsWindow'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:868: in function `UpdateTradeSkillWindow'
Interface\AddOns\Skillet-Classic\UI\Ma...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:1797: in function `UpdateDetailsWindow'
Interface\AddOns\Skillet-Classic\Skillet.lua:1267: in function `SetSelectedSkill'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lu...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
Interface\AddOns\Skillet-Classic\Skillet.lua:1266: in function `SetSelectedSkill'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:2227: in function `SkillButton_OnClick'
[string "*:OnClick"]:2: in function <[string...
AHDB Debug: Bad ItemLinkToId(nil) call. Stack:
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:26: in function `ItemLinkToId'
Interface\AddOns\AuctionDB\MoLib/MoLibAH.lua:88: in function `AHGetAuctionInfoByLink'
...terface\AddOns\Skillet-Classic\Plugins\AuctionDB.lua:173: in function `GetExtraText'
Interface\AddOns\Skillet-Classic\SkilletPlugin.lua:147: in function `GetExtraText'
...
Interface\AddOns\Skillet-Classic\Skillet.lua:1266: in function `SetSelectedSkill'
Interface\AddOns\Skillet-Classic\UI\MainFrame.lua:2227: in function `SkillButton_OnClick'
[string "*:OnClick"]:2: in function <[string...
AHDB AH closed
AHDB: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB AH closed
AHDB: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB AH closed
AHDB AH closed
AHDB: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: When at the AH: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB AH closed
AHDB: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB AH closed
AHDB AH closed
AHDB: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: Auction scan complete and captured for 10471 listings in 2.93 s (3572.2 auctions/sec).
407 new items in DB, now 3051 entries. 0 missing seller info.
MoLib AH Scan data packed 10471 auctions of 2446 items to 228.8 Kbytes
Scan context info: Alliance auction house on classic / Blaumeux
AHDB Warning: No realm DB yet for classic so using 'classic' as the region for now.
AH progress: 2 auctions missing info or seller, first one at 10380 / 10471
AH progress: 3 auctions missing info or seller, first one at 10264 / 10471
AH progress: 7 auctions missing info or seller, first one at 10192 / 10471
AH progress: 264 auctions missing info or seller, first one at 7474 / 10471
AH progress: 1611 auctions missing info or seller, first one at 5020 / 10471
AH progress: 2500 auctions missing info or seller, first one at 18 / 10471
AHDB New item #20 (2664): [Crested Scepter] 24 37 50 (maximum reached, won't show more for this scan)
AHDB New item #19 (2663): [Dark Iron Residue] 1 50
AHDB New item #18 (2662): [Solstice Staff of the Eagle] 11 34 20
AHDB New item #17 (2661): [Ivycloth Boots of the Falcon] 69 69
AHDB New item #16 (2660): [Raider's Belt of the Tiger] 23 69
AHDB New item #15 (2659): [Buccaneer's Gloves of the Owl] 46 69
AHDB New item #14 (2658): [Tracker's Boots of the Owl] 2 79
AHDB New item #13 (2657): [Large Knapsack] 2
AHDB New item #12 (2656): [Conjurer's Robe of the Eagle] 2 39
AHDB New item #11 (2655): [Icemail Jerkin] 9
AHDB New item #10 (2654): [Black Dragonscale] 18
AHDB New item #9 (2653): [Shimmering Gloves of Healing] 1 7 18
AHDB New item #8 (2652): [Schematic: EZ-Thro Dynamite II] 1 56 92
AHDB New item #7 (2651): [Huntsman's Shoulders of Intellect] 60
AHDB New item #6 (2650): [Formula: Enchant Bracer - Lesser Deflection] 2 10 90
AHDB New item #5 (2649): [Willow Pants of Fiery Wrath] 35
AHDB New item #4 (2648): [Twin-bladed Axe of Stamina] 34 19
AHDB New item #3 (2647): [High Councillor's Mantle of Shadow Wrath] 80
AHDB New item #2 (2646): [Regal Armor of the Whale] 2 20 1
AHDB New item #1 (2645): [Red Mageweave Pants] 3 32 2
AH progress: 2500 auctions missing info or seller, first one at 16 / 10471
AHDB: Getting 10471 items from AH all dump. (initial list took 0.91 sec to get)
AH Scan started... please wait...
AHDB: manual scan requested...
AHDB: click the button, or hit space or enter or IWT to Start a full scan (/ahdb scan)
AHDB: click the button, or hit space or enter or IWT to Target the Auctioneer (/tar auctioneer)
AHDB v1.02.00 by MooreaTv: type /ahdb for command list/help.

**Comment by mooreatv** [comment]
this would be for https://github.com/mooreatv/AuctionDB/issues

if still an issue open it there, thx
