### ISSUE TITLE
Where to config SQL info and go get is deprecated

### ISSUE THREAD

**Issue by GsynthChris** [mooreatv/AHDBapp#9]
Hi, Trying to figure this out and I'm a little lost. Where do I tell it where my SQL server is? 

Just an FYI, when I installed this it said "installing executables with 'go get' in module mode is deprecated"
```
C:\Users\Chris>go get github.com/mooreatv/AHDBapp
go: downloading github.com/mooreatv/AHDBapp v0.0.0-20201006170406-8287e5eedada
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading fortio.org/fortio v1.17.0
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by mooreatv** [comment]
it's deprecated but still works you could use `go install  github.com/mooreatv/AHDBapp` instead

**Comment by mooreatv** [comment]
> Hi, Trying to figure this out and I'm a little lost. Where do I tell it where my SQL server is?


https://github.com/mooreatv/AHDBapp#getting-started

`MYSQL_CONNECTION_INFO`
